/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c4a0125ae7876e617cb4df3139333e62)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	GENESIS_BASE_URL: "https://recons.rtrobotics.com";
	RECON_SESSIONS: DurableObjectNamespace<import("./worker/index").ReconstructionSession>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "ReconstructionSession";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GENESIS_BASE_URL">> {}
}
